const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const scriptPath = path.resolve(__dirname, '../scripts/verify-browser.js')

test('browser verifier uses an inline document and checks both comment actions across all stages', () => {
  assert.ok(fs.existsSync(scriptPath), 'scripts/verify-browser.js must exist')
  const source = fs.readFileSync(scriptPath, 'utf8')
  assert.match(source, /Page\.setDocumentContent/)
  assert.match(source, /outline-stage\.png/)
  assert.match(source, /draft-stage\.png/)
  assert.match(source, /layout-stage\.png/)
  assert.match(source, /submit-round/)
  assert.match(source, /add-comment/)
  assert.match(source, /comment-batch/)
  assert.match(source, /data-toggle-round/)
  assert.match(source, /historicalBatchCollapsed/)
  assert.match(source, /markerExpandedHistoricalBatch/)
  assert.match(source, /data-edit-page-content/)
  assert.match(source, /draft-stage-content-edit\.png/)
  assert.match(source, /pageContentManualEdit/)
  assert.match(source, /layoutTextSynchronized/)
  assert.match(source, /2026-09-01T10:08:00\.000Z/)
})
