
export const ERROR_CODES = Object.freeze({
  SCHEMA_INVALID: 'PRES_SCHEMA_INVALID',
  SCHEMA_VALIDATOR_UNAVAILABLE: 'PRES_SCHEMA_VALIDATOR_UNAVAILABLE',
  VERSION_UNSUPPORTED: 'PRES_VERSION_UNSUPPORTED',
  DIRECTORY_MISSING_REQUIRED_PATH: 'PRES_DIR_MISSING_REQUIRED_PATH',
  DIRECTORY_UNEXPECTED_TYPE: 'PRES_DIR_UNEXPECTED_TYPE',
  PROJECT_ID_MISMATCH: 'PRES_PROJECT_ID_MISMATCH',
  PROJECT_DIRECTORY_NAME_MISMATCH: 'PRES_PROJECT_DIRECTORY_NAME_MISMATCH',
  PATH_INVALID: 'PRES_PATH_INVALID',
  PATH_ABSOLUTE: 'PRES_PATH_ABSOLUTE',
  PATH_TRAVERSAL: 'PRES_PATH_TRAVERSAL',
  PATH_SEPARATOR_INVALID: 'PRES_PATH_SEPARATOR_INVALID',
  PATH_NOT_NFC: 'PRES_PATH_NOT_NFC',
  PATH_SYMLINK_FORBIDDEN: 'PRES_PATH_SYMLINK_FORBIDDEN',
  PATH_ESCAPE: 'PRES_PATH_ESCAPE',
  PATH_PORTABILITY_COLLISION: 'PRES_PATH_PORTABILITY_COLLISION',
  MANIFEST_FILE_MISSING: 'PRES_MANIFEST_FILE_MISSING',
  FILE_UNDECLARED: 'PRES_FILE_UNDECLARED',
  FILE_HASH_MISMATCH: 'PRES_FILE_HASH_MISMATCH',
  FILE_SIZE_MISMATCH: 'PRES_FILE_SIZE_MISMATCH',
  FILE_MIME_MISMATCH: 'PRES_FILE_MIME_MISMATCH',
  FILE_EXTENSION_MISMATCH: 'PRES_FILE_EXTENSION_MISMATCH',
  DUPLICATE_ID: 'PRES_DUPLICATE_ID',
  DUPLICATE_CONTENT: 'PRES_DUPLICATE_CONTENT',
  REFERENCE_NOT_FOUND: 'PRES_REFERENCE_NOT_FOUND',
  REFERENCE_WRONG_SCOPE: 'PRES_REFERENCE_WRONG_SCOPE',
  INPUT_INVALID: 'PRES_INPUT_INVALID',
})

export class PresentationContractError extends Error {
  constructor(code, message, details = undefined) {
    super(message)
    this.name = 'PresentationContractError'
    this.code = code
    if (details !== undefined) this.details = details
  }
}
